"""
Simple notification publisher using kafka-python.

Provides a lightweight helper to publish JSON events to a Kafka topic.
The producer is lazily initialized from environment variables so API code
can import and call `publish_event(...)` without managing connections.

Brief Description. Base file generated by Copilot, filled by LF, Copilot added comments afterwards.
"""
import os
import json
import logging
from typing import Any, Dict

from kafka import KafkaProducer

logger = logging.getLogger(__name__)

# Environment-configurable bootstrap servers (comma-separated)
KAFKA_BOOTSTRAP = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
NOTIFICATIONS_TOPIC = os.getenv("NOTIFICATIONS_TOPIC", "notifications")

# Lazy-initialized producer
_producer: KafkaProducer | None = None


def _get_producer() -> KafkaProducer:
    global _producer
    if _producer is None:
        logger.info("Initializing Kafka producer to %s", KAFKA_BOOTSTRAP)
        _producer = KafkaProducer(
            bootstrap_servers=KAFKA_BOOTSTRAP.split(","),
            value_serializer=lambda v: json.dumps(v).encode("utf-8"),
            retries=5,
        )
    return _producer


def publish_event(event_type: str, payload: Dict[str, Any]) -> None:
    """
    Publish a structured notification event to the notifications topic.

    event_type: short string indicating event, e.g. "user.registered"
    payload: JSON-serializable dict with event data
    """
    producer = _get_producer()
    event = {"type": event_type, "payload": payload}
    try:
        producer.send(NOTIFICATIONS_TOPIC, event)
        producer.flush(timeout=5)
        logger.debug("Published event %s -> %s", event_type, payload)
    except Exception as exc:  # pragma: no cover - runtime networking
        # Don't crash the API if Kafka is down; log the error.
        logger.exception("Failed to publish notification event: %s", exc)


from datetime import datetime, timezone
from typing import Any, Dict, List


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def password_changed_event(email: str) -> Dict[str, Any]:
    return {
        "event_type": "password_changed",
        "timestamp": _now_iso(),
        "to": [email],
        "subject": "Your password was changed",
        "template": "password_changed",
        "data": {},
    }


def offer_event(event_type: str, to_emails: List[str], offer_id: int, requested_game_id: int, offered_game_id: int, status: str) -> Dict[str, Any]:
    return {
        "event_type": event_type,
        "timestamp": _now_iso(),
        "to": to_emails,
        "subject": {
            "offer_created": "New trade offer",
            "offer_accepted": "Trade offer accepted",
            "offer_rejected": "Trade offer rejected",
        }.get(event_type, "Trade offer update"),
        "template": event_type,
        "data": {
            "offer_id": offer_id,
            "requested_game_id": requested_game_id,
            "offered_game_id": offered_game_id,
            "status": status,
        },
    }
